version: '3.8'

services:
  wb_bot:
    build: .
    container_name: wb_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:rw
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 