version: '3.8'

services:
  wb_bot:
    build: .
    container_name: wb_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./user_data:/app/user_data
      - ./.env:/app/.env:rw
    env_file:
      - .env 